// import { CategoryInterface } from '../types/category.interface';
// import { FoodInterface } from '../types/food.interface';

// let tempImage = ['../../../../assets/images/2.jpg'];

// const foodItems: FoodInterface[] = [
//   {
//     id: '1',
//     title: 'کباب اول',
//     ingredients: ['ماده ۲', 'ماده ۳', 'ماده ۴', 'ماده ۵'],
//     price: '60000',
//     imgSrc: [
//       '../../../../assets/images/1.jpg',
//       '../../../../assets/images/3.jpg',
//       '../../../../assets/images/4.jpg',
//     ],
//     isAddedToCart: false,
//     qty: 0,
//     categories: ['کباب'],
//     isDetailsShown: false,
//     shop: 'restaurant',
//   },
//   {
//     id: '2',
//     title: 'کوفته اول',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۴', 'ماده ۵'],
//     price: '30000',
//     imgSrc: [
//       '../../../../assets/images/3.jpg',
//       '../../../../assets/images/4.jpg',
//       '../../../../assets/images/5.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['کوفته'],
//     isDetailsShown: false,
//     shop: 'restaurant',
//   },
//   {
//     id: '3',
//     title: 'آش اول',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳'],
//     price: '20000',
//     imgSrc: [
//       '../../../../assets/images/4.jpg',
//       '../../../../assets/images/5.jpg',
//       '../../../../assets/images/6.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['آش'],
//     isDetailsShown: false,
//     shop: 'restaurant',
//   },
//   {
//     id: '4',
//     title: 'خوراک اول',
//     ingredients: ['ماده ۳', 'ماده ۴', 'ماده ۵'],
//     price: '80000',
//     imgSrc: [
//       '../../../../assets/images/5.jpg',
//       '../../../../assets/images/6.jpg',
//       '../../../../assets/images/7.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['خوراک'],
//     isDetailsShown: false,
//     shop: 'restaurant',
//   },
//   {
//     id: '5',
//     title: 'کوفته دوم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/6.jpg',
//       '../../../../assets/images/7.jpg',
//       '../../../../assets/images/8.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['کوفته'],
//     isDetailsShown: false,
//     shop: 'restaurant',
//   },
//   {
//     id: '11',
//     title: 'خورش دوم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/7.jpg',
//       '../../../../assets/images/8.jpg',
//       '../../../../assets/images/9.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['خورش'],
//     isDetailsShown: false,
//     shop: 'restaurant',
//   },
//   {
//     id: '12',
//     title: 'کباب دوم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/8.jpg',
//       '../../../../assets/images/9.jpg',
//       '../../../../assets/images/10.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['کباب'],
//     isDetailsShown: false,
//     shop: 'restaurant',
//   },
//   {
//     id: '13',
//     title: 'آش دوم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/9.jpg',
//       '../../../../assets/images/10.jpg',
//       '../../../../assets/images/11.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['آش'],
//     isDetailsShown: false,
//     shop: 'restaurant',
//   },
//   {
//     id: '14',
//     title: 'چلو و پلو اول',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/10.jpg',
//       '../../../../assets/images/11.jpg',
//       '../../../../assets/images/12.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['چلو و پلو'],
//     isDetailsShown: false,
//     shop: 'restaurant',
//   },
//   {
//     id: '15',
//     title: 'چلو و پلو دوم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/13.jpg',
//       '../../../../assets/images/14.jpg',
//       '../../../../assets/images/15.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['چلو و پلو'],
//     isDetailsShown: false,
//     shop: 'restaurant',
//   },
//   {
//     id: '16',
//     title: 'چلو و پلو سوم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/15.jpg',
//       '../../../../assets/images/1.jpg',
//       '../../../../assets/images/2.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['چلو و پلو'],
//     isDetailsShown: false,
//     shop: 'restaurant',
//   },
//   {
//     id: '17',
//     title: 'خورش چهارم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/1.jpg',
//       '../../../../assets/images/2.jpg',
//       '../../../../assets/images/3.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['خورش'],
//     isDetailsShown: false,
//     shop: 'restaurant',
//   },
//   {
//     id: '18',
//     title: 'آش پنجم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/2.jpg',
//       '../../../../assets/images/3.jpg',
//       '../../../../assets/images/4.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['آش'],
//     isDetailsShown: false,
//     shop: 'restaurant',
//   },
//   {
//     id: '6',
//     title: 'پیتزا چهارم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/3.jpg',
//       '../../../../assets/images/4.jpg',
//       '../../../../assets/images/5.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['پیتزا'],
//     isDetailsShown: false,
//     shop: 'fastFood',
//   },
//   {
//     id: '7',
//     title: 'ساندویچ اول',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/4.jpg',
//       '../../../../assets/images/5.jpg',
//       '../../../../assets/images/6.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['ساندویچ'],
//     isDetailsShown: false,
//     shop: 'fastFood',
//   },
//   {
//     id: '8',
//     title: 'همبرگر پنجم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/5.jpg',
//       '../../../../assets/images/6.jpg',
//       '../../../../assets/images/7.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['همبرگر'],
//     isDetailsShown: false,
//     shop: 'fastFood',
//   },
//   {
//     id: '19',
//     title: 'همبرگر اول',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/6.jpg',
//       '../../../../assets/images/7.jpg',
//       '../../../../assets/images/8.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['همبرگر'],
//     isDetailsShown: false,
//     shop: 'fastFood',
//   },
//   {
//     id: '20',
//     title: 'همبرگر دوم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/7.jpg',
//       '../../../../assets/images/8.jpg',
//       '../../../../assets/images/9.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['همبرگر'],
//     isDetailsShown: false,
//     shop: 'fastFood',
//   },
//   {
//     id: '21',
//     title: 'همبرگر سوم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/8.jpg',
//       '../../../../assets/images/9.jpg',
//       '../../../../assets/images/10.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['همبرگر'],
//     isDetailsShown: false,
//     shop: 'fastFood',
//   },
//   {
//     id: '22',
//     title: 'پیتزا اول',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/9.jpg',
//       '../../../../assets/images/10.jpg',
//       '../../../../assets/images/11.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['پیتزا'],
//     isDetailsShown: false,
//     shop: 'fastFood',
//   },
//   {
//     id: '23',
//     title: 'پیتزا دوم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/10.jpg',
//       '../../../../assets/images/11.jpg',
//       '../../../../assets/images/12.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['پیتزا'],
//     isDetailsShown: false,
//     shop: 'fastFood',
//   },
//   {
//     id: '24',
//     title: 'سمبوسه اول',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/11.jpg',
//       '../../../../assets/images/12.jpg',
//       '../../../../assets/images/13.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['سمبوسه'],
//     isDetailsShown: false,
//     shop: 'fastFood',
//   },
//   {
//     id: '25',
//     title: 'سمبوسه دوم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/12.jpg',
//       '../../../../assets/images/13.jpg',
//       '../../../../assets/images/14.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['سمبوسه 3'],
//     isDetailsShown: false,
//     shop: 'fastFood',
//   },
//   {
//     id: '9',
//     title: 'چای سبز',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/13.jpg',
//       '../../../../assets/images/14.jpg',
//       '../../../../assets/images/15.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['چای'],
//     isDetailsShown: false,
//     shop: 'coffeeShop',
//   },
//   {
//     id: '10',
//     title: 'بستنی اول',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/14.jpg',
//       '../../../../assets/images/15.jpg',
//       '../../../../assets/images/1.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['بستنی'],
//     isDetailsShown: false,
//     shop: 'coffeeShop',
//   },
//   {
//     id: '26',
//     title: 'بستنی دوم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/15.jpg',
//       '../../../../assets/images/1.jpg',
//       '../../../../assets/images/2.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['بستنی'],
//     isDetailsShown: false,
//     shop: 'coffeeShop',
//   },
//   {
//     id: '27',
//     title: 'چای سیاه',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/1.jpg',
//       '../../../../assets/images/2.jpg',
//       '../../../../assets/images/3.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['چای'],
//     isDetailsShown: false,
//     shop: 'coffeeShop',
//   },
//   {
//     id: '28',
//     title: 'قهوه اول',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/2.jpg',
//       '../../../../assets/images/3.jpg',
//       '../../../../assets/images/4.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['قهوه'],
//     isDetailsShown: false,
//     shop: 'coffeeShop',
//   },
//   {
//     id: '29',
//     title: 'قهوه سوم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/3.jpg',
//       '../../../../assets/images/4.jpg',
//       '../../../../assets/images/5.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['قهوه'],
//     isDetailsShown: false,
//     shop: 'coffeeShop',
//   },
//   {
//     id: '30',
//     title: 'شیک اول',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/4.jpg',
//       '../../../../assets/images/5.jpg',
//       '../../../../assets/images/6.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['شیک'],
//     isDetailsShown: false,
//     shop: 'coffeeShop',
//   },
//   {
//     id: '31',
//     title: 'شیک دوم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/5.jpg',
//       '../../../../assets/images/6.jpg',
//       '../../../../assets/images/7.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['شیک'],
//     isDetailsShown: false,
//     shop: 'coffeeShop',
//   },
//   {
//     id: '32',
//     title: 'شیک سوم',
//     ingredients: ['ماده ۱', 'ماده ۲', 'ماده ۳', 'ماده ۵'],
//     price: '12000',
//     imgSrc: [
//       '../../../../assets/images/6.jpg',
//       '../../../../assets/images/7.jpg',
//       '../../../../assets/images/8.jpg',
//     ],

//     isAddedToCart: false,
//     qty: 0,
//     categories: ['شیک'],
//     isDetailsShown: false,
//     shop: 'coffeeShop',
//   },
// ];

// const categories: CategoryInterface[] = [
//   {
//     title: 'آش',
//     imgSrc: '../../../../assets/images/2.jpg',

//     isActive: false,
//     shopType: 'restaurant',
//   },
//   {
//     title: 'خوراک',
//     imgSrc: '../../../../assets/images/3.jpg',

//     isActive: false,
//     shopType: 'restaurant',
//   },
//   {
//     title: 'چلو و پلو',
//     imgSrc: '../../../../assets/images/4.jpg',

//     isActive: false,
//     shopType: 'restaurant',
//   },
//   {
//     title: 'کوفته',
//     imgSrc: '../../../../assets/images/5.jpg',

//     isActive: false,
//     shopType: 'restaurant',
//   },
//   {
//     title: 'کباب',
//     imgSrc: '../../../../assets/images/6.jpg',

//     isActive: false,
//     shopType: 'restaurant',
//   },
//   {
//     title: 'خورش',
//     imgSrc: '../../../../assets/images/7.jpg',

//     isActive: false,
//     shopType: 'restaurant',
//   },
//   {
//     title: 'قهوه',
//     imgSrc: '../../../../assets/images/8.jpg',

//     isActive: false,
//     shopType: 'coffeeShop',
//   },
//   {
//     title: 'چای',
//     imgSrc: '../../../../assets/images/9.jpg',

//     isActive: false,
//     shopType: 'coffeeShop',
//   },
//   {
//     title: 'بستنی',
//     imgSrc: '../../../../assets/images/10.jpg',

//     isActive: false,
//     shopType: 'coffeeShop',
//   },
//   {
//     title: 'شیک',
//     imgSrc: '../../../../assets/images/11.jpg',

//     isActive: false,
//     shopType: 'coffeeShop',
//   },
//   {
//     title: 'پیتزا',
//     imgSrc: '../../../../assets/images/12.jpg',

//     isActive: false,
//     shopType: 'fastFood',
//   },
//   {
//     title: 'ساندویچ',
//     imgSrc: '../../../../assets/images/13.jpg',

//     isActive: false,
//     shopType: 'fastFood',
//   },
//   {
//     title: 'همبرگر',
//     imgSrc: '../../../../assets/images/14.jpg',

//     isActive: false,
//     shopType: 'fastFood',
//   },
//   {
//     title: 'سمبوسه',
//     imgSrc: '../../../../assets/images/15.jpg',

//     isActive: false,
//     shopType: 'fastFood',
//   },
// ];

// export { foodItems, categories };
export const mockApi = {
  returnCode: 0,
  data: {
    categories: [
      {
        id: 212,
        topic: 'پیتزا',
        topicEn: '',
        topicAr: '',
        localCategoryId: 3,
        active: true,
        displayOrder: 2,
        imageName: 'C-212.png',
        imageUrl: 'https://store.nikukiosk.com/image/C-212.png',
        imageLastUpdate: '2022-10-18 17:13:07',
        store: {
          id: 517,
          name: 'پیتزا یاقوت',
          smsExpireTimeSeconds: 300,
          smsIntervalTimeSeconds: 60,
          samanTerminalId: '',
          mellatTerminalId: '5923332',
          paymentCallbackUrl:
            'https://store.nikukiosk.com/remoteApi/web/v1/handlePaymentResult',
          mellatUsername: 'pizzayaghoot1400',
          mellatPassword: '73973239',
          paymentResultPage: 'https://pizzayaghoot.com/payment-result?',
          smsServiceName: 'homa',
          smsHomaPortalCode: '10014033',
          smsHomaUsername: 'fr47880',
          smsHomaPassword: '95760',
          smsVerificationCodeText: '%s-پیتزا یاقوت',
          smsSuccessPurchaseText:
            'مشتری گرامی، خرید شما به شماره %s با موفقیت ثبت شد.(پیتزا یاقوت)',
          smsKavenegarApiKey:
            '695646716D42345578646871644351327246656C4F332B7948474E51733754597777736F566A567A5937673D',
          verifySmsKavenegarTemplate: 'verifypizzayaghoot',
          successOrderSmsKavenegarTemplate: 'successorderpizzayaghoot',
          fromTime: '08:00:00',
          toTime: '23:59:00',
          addProductFromWeb: false,
          editProductTopicFromWeb: false,
          editProductDescriptionFromWeb: false,
          editProductCategoryFromWeb: false,
          editProductActiveFromWeb: false,
          editProductDisplayOrderFromWeb: false,
          editProductPriceFromWeb: true,
          editProductBespokensFromWeb: false,
          editProductImageFromWeb: true,
          addCategoryFromWeb: true,
          editCategoryTopicFromWeb: false,
          editCategoryParentCategoryFromWeb: false,
          editCategoryActiveFromWeb: true,
          editCategoryDisplayOrderFromWeb: false,
          editCategoryImageFromWeb: true,
          addBespokenFromWeb: false,
          editBespokenTopicFromWeb: false,
          editBespokenActiveFromWeb: false,
          editBespokenPriceFromWeb: false,
        },
      },
      {
        id: 211,
        topic: 'برگر',
        topicEn: '',
        topicAr: '',
        localCategoryId: 2,
        active: true,
        displayOrder: 3,
        imageName: 'C-211.png',
        imageUrl: 'https://store.nikukiosk.com/image/C-211.png',
        imageLastUpdate: '2022-10-18 17:13:54',
        store: {
          id: 517,
          name: 'پیتزا یاقوت',
          smsExpireTimeSeconds: 300,
          smsIntervalTimeSeconds: 60,
          samanTerminalId: '',
          mellatTerminalId: '5923332',
          paymentCallbackUrl:
            'https://store.nikukiosk.com/remoteApi/web/v1/handlePaymentResult',
          mellatUsername: 'pizzayaghoot1400',
          mellatPassword: '73973239',
          paymentResultPage: 'https://pizzayaghoot.com/payment-result?',
          smsServiceName: 'homa',
          smsHomaPortalCode: '10014033',
          smsHomaUsername: 'fr47880',
          smsHomaPassword: '95760',
          smsVerificationCodeText: '%s-پیتزا یاقوت',
          smsSuccessPurchaseText:
            'مشتری گرامی، خرید شما به شماره %s با موفقیت ثبت شد.(پیتزا یاقوت)',
          smsKavenegarApiKey:
            '695646716D42345578646871644351327246656C4F332B7948474E51733754597777736F566A567A5937673D',
          verifySmsKavenegarTemplate: 'verifypizzayaghoot',
          successOrderSmsKavenegarTemplate: 'successorderpizzayaghoot',
          fromTime: '08:00:00',
          toTime: '23:59:00',
          addProductFromWeb: false,
          editProductTopicFromWeb: false,
          editProductDescriptionFromWeb: false,
          editProductCategoryFromWeb: false,
          editProductActiveFromWeb: false,
          editProductDisplayOrderFromWeb: false,
          editProductPriceFromWeb: true,
          editProductBespokensFromWeb: false,
          editProductImageFromWeb: true,
          addCategoryFromWeb: true,
          editCategoryTopicFromWeb: false,
          editCategoryParentCategoryFromWeb: false,
          editCategoryActiveFromWeb: true,
          editCategoryDisplayOrderFromWeb: false,
          editCategoryImageFromWeb: true,
          addBespokenFromWeb: false,
          editBespokenTopicFromWeb: false,
          editBespokenActiveFromWeb: false,
          editBespokenPriceFromWeb: false,
        },
      },
      {
        id: 217,
        topic: 'ساندویچ',
        topicEn: '',
        topicAr: '',
        localCategoryId: 8,
        active: true,
        displayOrder: 4,
        imageName: 'C-217.png',
        imageUrl: 'https://store.nikukiosk.com/image/C-217.png',
        imageLastUpdate: '2022-10-18 17:13:40',
        store: {
          id: 517,
          name: 'پیتزا یاقوت',
          smsExpireTimeSeconds: 300,
          smsIntervalTimeSeconds: 60,
          samanTerminalId: '',
          mellatTerminalId: '5923332',
          paymentCallbackUrl:
            'https://store.nikukiosk.com/remoteApi/web/v1/handlePaymentResult',
          mellatUsername: 'pizzayaghoot1400',
          mellatPassword: '73973239',
          paymentResultPage: 'https://pizzayaghoot.com/payment-result?',
          smsServiceName: 'homa',
          smsHomaPortalCode: '10014033',
          smsHomaUsername: 'fr47880',
          smsHomaPassword: '95760',
          smsVerificationCodeText: '%s-پیتزا یاقوت',
          smsSuccessPurchaseText:
            'مشتری گرامی، خرید شما به شماره %s با موفقیت ثبت شد.(پیتزا یاقوت)',
          smsKavenegarApiKey:
            '695646716D42345578646871644351327246656C4F332B7948474E51733754597777736F566A567A5937673D',
          verifySmsKavenegarTemplate: 'verifypizzayaghoot',
          successOrderSmsKavenegarTemplate: 'successorderpizzayaghoot',
          fromTime: '08:00:00',
          toTime: '23:59:00',
          addProductFromWeb: false,
          editProductTopicFromWeb: false,
          editProductDescriptionFromWeb: false,
          editProductCategoryFromWeb: false,
          editProductActiveFromWeb: false,
          editProductDisplayOrderFromWeb: false,
          editProductPriceFromWeb: true,
          editProductBespokensFromWeb: false,
          editProductImageFromWeb: true,
          addCategoryFromWeb: true,
          editCategoryTopicFromWeb: false,
          editCategoryParentCategoryFromWeb: false,
          editCategoryActiveFromWeb: true,
          editCategoryDisplayOrderFromWeb: false,
          editCategoryImageFromWeb: true,
          addBespokenFromWeb: false,
          editBespokenTopicFromWeb: false,
          editBespokenActiveFromWeb: false,
          editBespokenPriceFromWeb: false,
        },
      },
      {
        id: 213,
        topic: 'پیش غذا',
        topicEn: '',
        topicAr: '',
        localCategoryId: 4,
        active: true,
        displayOrder: 5,
        imageName: 'C-213.png',
        imageUrl: 'https://store.nikukiosk.com/image/C-213.png',
        imageLastUpdate: '2022-10-18 17:12:48',
        store: {
          id: 517,
          name: 'پیتزا یاقوت',
          smsExpireTimeSeconds: 300,
          smsIntervalTimeSeconds: 60,
          samanTerminalId: '',
          mellatTerminalId: '5923332',
          paymentCallbackUrl:
            'https://store.nikukiosk.com/remoteApi/web/v1/handlePaymentResult',
          mellatUsername: 'pizzayaghoot1400',
          mellatPassword: '73973239',
          paymentResultPage: 'https://pizzayaghoot.com/payment-result?',
          smsServiceName: 'homa',
          smsHomaPortalCode: '10014033',
          smsHomaUsername: 'fr47880',
          smsHomaPassword: '95760',
          smsVerificationCodeText: '%s-پیتزا یاقوت',
          smsSuccessPurchaseText:
            'مشتری گرامی، خرید شما به شماره %s با موفقیت ثبت شد.(پیتزا یاقوت)',
          smsKavenegarApiKey:
            '695646716D42345578646871644351327246656C4F332B7948474E51733754597777736F566A567A5937673D',
          verifySmsKavenegarTemplate: 'verifypizzayaghoot',
          successOrderSmsKavenegarTemplate: 'successorderpizzayaghoot',
          fromTime: '08:00:00',
          toTime: '23:59:00',
          addProductFromWeb: false,
          editProductTopicFromWeb: false,
          editProductDescriptionFromWeb: false,
          editProductCategoryFromWeb: false,
          editProductActiveFromWeb: false,
          editProductDisplayOrderFromWeb: false,
          editProductPriceFromWeb: true,
          editProductBespokensFromWeb: false,
          editProductImageFromWeb: true,
          addCategoryFromWeb: true,
          editCategoryTopicFromWeb: false,
          editCategoryParentCategoryFromWeb: false,
          editCategoryActiveFromWeb: true,
          editCategoryDisplayOrderFromWeb: false,
          editCategoryImageFromWeb: true,
          addBespokenFromWeb: false,
          editBespokenTopicFromWeb: false,
          editBespokenActiveFromWeb: false,
          editBespokenPriceFromWeb: false,
        },
      },
      {
        id: 214,
        topic: 'نوشیدنی',
        topicEn: '',
        topicAr: '',
        localCategoryId: 5,
        active: true,
        displayOrder: 7,
        imageName: 'C-214.png',
        imageUrl: 'https://store.nikukiosk.com/image/C-214.png',
        imageLastUpdate: '2022-10-18 17:13:22',
        store: {
          id: 517,
          name: 'پیتزا یاقوت',
          smsExpireTimeSeconds: 300,
          smsIntervalTimeSeconds: 60,
          samanTerminalId: '',
          mellatTerminalId: '5923332',
          paymentCallbackUrl:
            'https://store.nikukiosk.com/remoteApi/web/v1/handlePaymentResult',
          mellatUsername: 'pizzayaghoot1400',
          mellatPassword: '73973239',
          paymentResultPage: 'https://pizzayaghoot.com/payment-result?',
          smsServiceName: 'homa',
          smsHomaPortalCode: '10014033',
          smsHomaUsername: 'fr47880',
          smsHomaPassword: '95760',
          smsVerificationCodeText: '%s-پیتزا یاقوت',
          smsSuccessPurchaseText:
            'مشتری گرامی، خرید شما به شماره %s با موفقیت ثبت شد.(پیتزا یاقوت)',
          smsKavenegarApiKey:
            '695646716D42345578646871644351327246656C4F332B7948474E51733754597777736F566A567A5937673D',
          verifySmsKavenegarTemplate: 'verifypizzayaghoot',
          successOrderSmsKavenegarTemplate: 'successorderpizzayaghoot',
          fromTime: '08:00:00',
          toTime: '23:59:00',
          addProductFromWeb: false,
          editProductTopicFromWeb: false,
          editProductDescriptionFromWeb: false,
          editProductCategoryFromWeb: false,
          editProductActiveFromWeb: false,
          editProductDisplayOrderFromWeb: false,
          editProductPriceFromWeb: true,
          editProductBespokensFromWeb: false,
          editProductImageFromWeb: true,
          addCategoryFromWeb: true,
          editCategoryTopicFromWeb: false,
          editCategoryParentCategoryFromWeb: false,
          editCategoryActiveFromWeb: true,
          editCategoryDisplayOrderFromWeb: false,
          editCategoryImageFromWeb: true,
          addBespokenFromWeb: false,
          editBespokenTopicFromWeb: false,
          editBespokenActiveFromWeb: false,
          editBespokenPriceFromWeb: false,
        },
      },
    ],
    products: [
      {
        id: 1026,
        topic: 'همبرگر مخصوص',
        topicEn: '',
        topicAr: '',
        description:
          'نان مخصوص همبرگر-1عددهمبرگرگوشت گرم-گوجه-خیارشور-کاهو- سس مایونز-سس کچاپ',
        metaDescription:
          'نان مخصوص همبرگر-1عددهمبرگرگوشت گرم-گوجه-خیارشور-کاهو- سس مایونز-سس کچاپ',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 2,
        localProductId: 13,
        active: true,
        displayOrder: 1,
        price: 550000,
        discountPrice: 467500,
        oldPrice: 0,
        smallImageName: '1026-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1026-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:06',
        display: false,
        category: {
          id: 211,
          topic: 'برگر',
          topicEn: '',
          topicAr: '',
          localCategoryId: 2,
          active: true,
          displayOrder: 3,
          imageName: 'C-211.png',
          imageLastUpdate: '2022-10-18 17:13:54',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1015,
        topic: 'همبرگر زغالی',
        topicEn: '',
        topicAr: '',
        description:
          'نان مخصوص همبرگر-1عددهمبرگرگوشت گرم-گوجه-خیارشور-کاهو- سس مایونز-سس کچاپ',
        metaDescription:
          'نان مخصوص همبرگر-1عددهمبرگرگوشت گرم-گوجه-خیارشور-کاهو- سس مایونز-سس کچاپ',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 2,
        localProductId: 2,
        active: true,
        displayOrder: 2,
        price: 550000,
        discountPrice: 467500,
        oldPrice: 0,
        smallImageName: '1015-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1015-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:40:58',
        display: false,
        category: {
          id: 211,
          topic: 'برگر',
          topicEn: '',
          topicAr: '',
          localCategoryId: 2,
          active: true,
          displayOrder: 3,
          imageName: 'C-211.png',
          imageLastUpdate: '2022-10-18 17:13:54',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1018,
        topic: 'چیز برگر',
        topicEn: '',
        topicAr: '',
        description:
          'نان مخصوص همبرگر-1عددهمبرگرگوشت گرم--1عددپنیرورقه ای-گوجه-خیارشور-کاهو- سس کچاپ- سس مایونز',
        metaDescription:
          'نان مخصوص همبرگر-1عددهمبرگرگوشت گرم--1عددپنیرورقه ای-گوجه-خیارشور-کاهو- سس کچاپ- سس مایونز',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 2,
        localProductId: 5,
        active: true,
        displayOrder: 3,
        price: 680000,
        discountPrice: 578000,
        oldPrice: 0,
        smallImageName: '1018-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1018-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:01',
        display: false,
        category: {
          id: 211,
          topic: 'برگر',
          topicEn: '',
          topicAr: '',
          localCategoryId: 2,
          active: true,
          displayOrder: 3,
          imageName: 'C-211.png',
          imageLastUpdate: '2022-10-18 17:13:54',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 23,
            topic: 'پنیراضافه',
            price: 50000,
            localBespokenId: 7,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1027,
        topic: 'رویال برگر',
        topicEn: '',
        topicAr: '',
        description:
          'نان مخصوص همبرگر-1عددهمبرگرگوشت گرم-1ورقه کالباس ژامبون -1عددپنیرورقه ای-گوجه-خیارشور-کاهو- سس کچاپ- سس مایونز',
        metaDescription:
          'نان مخصوص همبرگر-1عددهمبرگرگوشت گرم-1ورقه کالباس ژامبون -1عددپنیرورقه ای-گوجه-خیارشور-کاهو- سس کچاپ- سس مایونز',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 2,
        localProductId: 14,
        active: true,
        displayOrder: 4,
        price: 700000,
        discountPrice: 595000,
        oldPrice: 0,
        smallImageName: '1027-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1027-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:07',
        display: false,
        category: {
          id: 211,
          topic: 'برگر',
          topicEn: '',
          topicAr: '',
          localCategoryId: 2,
          active: true,
          displayOrder: 3,
          imageName: 'C-211.png',
          imageLastUpdate: '2022-10-18 17:13:54',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 23,
            topic: 'پنیراضافه',
            price: 50000,
            localBespokenId: 7,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1017,
        topic: 'قارچ برگر',
        topicEn: '',
        topicAr: '',
        description:
          'نان مخصوص همبرگر-1عددهمبرگرگوشت گرم-قارچ-پنیرمخصوص-گوجه-خیارشور-کاهو- سس کچاپ- سس مایونز',
        metaDescription:
          'نان مخصوص همبرگر-1عددهمبرگرگوشت گرم-قارچ-پنیرمخصوص-گوجه-خیارشور-کاهو- سس کچاپ- سس مایونز',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 2,
        localProductId: 4,
        active: true,
        displayOrder: 5,
        price: 750000,
        discountPrice: 637500,
        oldPrice: 0,
        smallImageName: '1017-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1017-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:00',
        display: false,
        category: {
          id: 211,
          topic: 'برگر',
          topicEn: '',
          topicAr: '',
          localCategoryId: 2,
          active: true,
          displayOrder: 3,
          imageName: 'C-211.png',
          imageLastUpdate: '2022-10-18 17:13:54',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 23,
            topic: 'پنیراضافه',
            price: 50000,
            localBespokenId: 7,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1028,
        topic: 'دوبل چیز برگر',
        topicEn: '',
        topicAr: '',
        description:
          'نان مخصوص همبرگر-2عددهمبرگرگوشت گرم--2عددپنیرورقه ای-گوجه-خیارشور-کاهو- سس کچاپ- سس مایونز',
        metaDescription:
          'نان مخصوص همبرگر-2عددهمبرگرگوشت گرم--2عددپنیرورقه ای-گوجه-خیارشور-کاهو- سس کچاپ- سس مایونز',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 2,
        localProductId: 15,
        active: true,
        displayOrder: 6,
        price: 950000,
        discountPrice: 807500,
        oldPrice: 0,
        smallImageName: '1028-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1028-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:07',
        display: false,
        category: {
          id: 211,
          topic: 'برگر',
          topicEn: '',
          topicAr: '',
          localCategoryId: 2,
          active: true,
          displayOrder: 3,
          imageName: 'C-211.png',
          imageLastUpdate: '2022-10-18 17:13:54',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 23,
            topic: 'پنیراضافه',
            price: 50000,
            localBespokenId: 7,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1147,
        topic: 'پیتزا مخصوص پنجره ای دو نفره',
        topicEn: '',
        topicAr: '',
        description:
          'خمیر-سس مخصوص -پنیرپیتزا-کالباس مخصوص-فلفل دلمه- قارچ-سوسیس-گوشت',
        metaDescription:
          'خمیر-سس مخصوص -پنیرپیتزا-کالباس مخصوص-فلفل دلمه- قارچ-سوسیس-گوشت',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 3,
        localProductId: 54,
        active: true,
        displayOrder: 1,
        price: 1400000,
        discountPrice: 1190000,
        oldPrice: 0,
        smallImageName: '1147-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1147-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:35',
        display: false,
        category: {
          id: 212,
          topic: 'پیتزا',
          topicEn: '',
          topicAr: '',
          localCategoryId: 3,
          active: true,
          displayOrder: 2,
          imageName: 'C-212.png',
          imageLastUpdate: '2022-10-18 17:13:07',
        },
        bespokens: [],
        productImages: [],
      },
      {
        id: 1158,
        topic: 'پیتزا گوشت قارچ 2نفره',
        topicEn: '',
        topicAr: '',
        description:
          'خمیرمخصوص -سس مخصوص -گوشت طعم دارشده-پنیرپیتزامخصوص-فلفل دلمه-قارچ-سس کچاپ',
        metaDescription:
          'خمیرمخصوص -سس مخصوص -گوشت طعم دارشده-پنیرپیتزامخصوص-فلفل دلمه-قارچ-سس کچاپ',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 3,
        localProductId: 56,
        active: true,
        displayOrder: 2,
        price: 1500000,
        discountPrice: 1275000,
        oldPrice: 0,
        smallImageName: '1158-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1158-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:37',
        display: false,
        category: {
          id: 212,
          topic: 'پیتزا',
          topicEn: '',
          topicAr: '',
          localCategoryId: 3,
          active: true,
          displayOrder: 2,
          imageName: 'C-212.png',
          imageLastUpdate: '2022-10-18 17:13:07',
        },
        bespokens: [
          {
            id: 21,
            topic: 'بدون فلفل',
            price: 0,
            localBespokenId: 5,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1157,
        topic: 'پیتزامرغ قارچ2نفره',
        topicEn: '',
        topicAr: '',
        description:
          'خمیرمخصوص -سس مخصوص - فیله مرغ طعم دارشده -قارچ -پنیرپیتزا مخصوص -فلفل دلمه -سس کچاپ',
        metaDescription:
          'خمیرمخصوص -سس مخصوص - فیله مرغ طعم دارشده -قارچ -پنیرپیتزا مخصوص -فلفل دلمه -سس کچاپ',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 3,
        localProductId: 55,
        active: true,
        displayOrder: 3,
        price: 1380000,
        discountPrice: 1173000,
        oldPrice: 0,
        smallImageName: '1157-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1157-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:36',
        display: false,
        category: {
          id: 212,
          topic: 'پیتزا',
          topicEn: '',
          topicAr: '',
          localCategoryId: 3,
          active: true,
          displayOrder: 2,
          imageName: 'C-212.png',
          imageLastUpdate: '2022-10-18 17:13:07',
        },
        bespokens: [
          {
            id: 21,
            topic: 'بدون فلفل',
            price: 0,
            localBespokenId: 5,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1040,
        topic: 'پیتزا مرغ و قارچ',
        topicEn: '',
        topicAr: '',
        description:
          'خمیرمخصوص -سس مخصوص - فیله مرغ طعم دارشده -قارچ -پنیرپیتزا مخصوص -فلفل دلمه -سس کچاپ',
        metaDescription:
          'خمیرمخصوص -سس مخصوص - فیله مرغ طعم دارشده -قارچ -پنیرپیتزا مخصوص -فلفل دلمه -سس کچاپ',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 3,
        localProductId: 27,
        active: true,
        displayOrder: 4,
        price: 1200000,
        discountPrice: 1020000,
        oldPrice: 0,
        smallImageName: '1040-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1040-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:14',
        display: false,
        category: {
          id: 212,
          topic: 'پیتزا',
          topicEn: '',
          topicAr: '',
          localCategoryId: 3,
          active: true,
          displayOrder: 2,
          imageName: 'C-212.png',
          imageLastUpdate: '2022-10-18 17:13:07',
        },
        bespokens: [
          {
            id: 21,
            topic: 'بدون فلفل',
            price: 0,
            localBespokenId: 5,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1039,
        topic: 'پیتزا گوشت و قارچ',
        topicEn: '',
        topicAr: '',
        description:
          'خمیرمخصوص -سس مخصوص -گوشت طعم دارشده-پنیرپیتزامخصوص-فلفل دلمه-قارچ-سس کچاپ',
        metaDescription:
          'خمیرمخصوص -سس مخصوص -گوشت طعم دارشده-پنیرپیتزامخصوص-فلفل دلمه-قارچ-سس کچاپ',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 3,
        localProductId: 26,
        active: true,
        displayOrder: 5,
        price: 1280000,
        discountPrice: 1088000,
        oldPrice: 0,
        smallImageName: '1039-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1039-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:13',
        display: false,
        category: {
          id: 212,
          topic: 'پیتزا',
          topicEn: '',
          topicAr: '',
          localCategoryId: 3,
          active: true,
          displayOrder: 2,
          imageName: 'C-212.png',
          imageLastUpdate: '2022-10-18 17:13:07',
        },
        bespokens: [
          {
            id: 21,
            topic: 'بدون فلفل',
            price: 0,
            localBespokenId: 5,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1038,
        topic: 'پیتزا پپرونی',
        topicEn: '',
        topicAr: '',
        description:
          'خمیرمخصوص -سس مخصوص -کالباس پپرونی -پنیرپیتزامخصوص-فلفل دلمه-قارچ-سس کچاپ',
        metaDescription:
          'خمیرمخصوص -سس مخصوص -کالباس پپرونی -پنیرپیتزامخصوص-فلفل دلمه-قارچ-سس کچاپ',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 3,
        localProductId: 25,
        active: true,
        displayOrder: 6,
        price: 1020000,
        discountPrice: 867000,
        oldPrice: 0,
        smallImageName: '1038-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1038-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:12',
        display: false,
        category: {
          id: 212,
          topic: 'پیتزا',
          topicEn: '',
          topicAr: '',
          localCategoryId: 3,
          active: true,
          displayOrder: 2,
          imageName: 'C-212.png',
          imageLastUpdate: '2022-10-18 17:13:07',
        },
        bespokens: [
          {
            id: 20,
            topic: 'بدون قارچ',
            price: 0,
            localBespokenId: 4,
            active: true,
          },
          {
            id: 21,
            topic: 'بدون فلفل',
            price: 0,
            localBespokenId: 5,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1036,
        topic: 'پیتزا مخصوص پنجره ای',
        topicEn: '',
        topicAr: '',
        description:
          'خمیر-سس مخصوص -پنیرپیتزا-کالباس مخصوص--فلفل دلمه- قارچ-سوسیس-گوشت',
        metaDescription:
          'خمیر-سس مخصوص -پنیرپیتزا-کالباس مخصوص--فلفل دلمه- قارچ-سوسیس-گوشت',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 3,
        localProductId: 23,
        active: true,
        displayOrder: 7,
        price: 1100000,
        discountPrice: 935000,
        oldPrice: 0,
        smallImageName: '1036-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1036-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:11',
        display: false,
        category: {
          id: 212,
          topic: 'پیتزا',
          topicEn: '',
          topicAr: '',
          localCategoryId: 3,
          active: true,
          displayOrder: 2,
          imageName: 'C-212.png',
          imageLastUpdate: '2022-10-18 17:13:07',
        },
        bespokens: [
          {
            id: 20,
            topic: 'بدون قارچ',
            price: 0,
            localBespokenId: 4,
            active: true,
          },
          {
            id: 21,
            topic: 'بدون فلفل',
            price: 0,
            localBespokenId: 5,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1037,
        topic: 'پیتزا مخلوط',
        topicEn: '',
        topicAr: '',
        description:
          'خمیرمخصوص -سس مخصوص -کالباس خشک -پنیرپیتزامخصوص-فلفل دلمه-قارچ-سس کچاپ',
        metaDescription:
          'خمیرمخصوص -سس مخصوص -کالباس خشک -پنیرپیتزامخصوص-فلفل دلمه-قارچ-سس کچاپ',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 3,
        localProductId: 24,
        active: true,
        displayOrder: 8,
        price: 1000000,
        discountPrice: 850000,
        oldPrice: 0,
        smallImageName: '1037-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1037-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:12',
        display: false,
        category: {
          id: 212,
          topic: 'پیتزا',
          topicEn: '',
          topicAr: '',
          localCategoryId: 3,
          active: true,
          displayOrder: 2,
          imageName: 'C-212.png',
          imageLastUpdate: '2022-10-18 17:13:07',
        },
        bespokens: [
          {
            id: 20,
            topic: 'بدون قارچ',
            price: 0,
            localBespokenId: 4,
            active: true,
          },
          {
            id: 21,
            topic: 'بدون فلفل',
            price: 0,
            localBespokenId: 5,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1043,
        topic: 'پیتزا مینی مرغ و قارچ',
        topicEn: '',
        topicAr: '',
        description:
          'خمیرمخصوص -سس مخصوص - فیله مرغ طعم دارشده -قارچ -پنیرپیتزا مخصوص -فلفل دلمه -سس کچاپ',
        metaDescription:
          'خمیرمخصوص -سس مخصوص - فیله مرغ طعم دارشده -قارچ -پنیرپیتزا مخصوص -فلفل دلمه -سس کچاپ',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 3,
        localProductId: 30,
        active: true,
        displayOrder: 9,
        price: 750000,
        discountPrice: 637500,
        oldPrice: 0,
        smallImageName: '1043-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1043-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:15',
        display: false,
        category: {
          id: 212,
          topic: 'پیتزا',
          topicEn: '',
          topicAr: '',
          localCategoryId: 3,
          active: true,
          displayOrder: 2,
          imageName: 'C-212.png',
          imageLastUpdate: '2022-10-18 17:13:07',
        },
        bespokens: [
          {
            id: 21,
            topic: 'بدون فلفل',
            price: 0,
            localBespokenId: 5,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1041,
        topic: 'پیتزا مینی مخصوص',
        topicEn: '',
        topicAr: '',
        description:
          'خمیرمخصوص -سس مخصوص-کالباس مخصوص-پنیرپیتزامخصوص -سوسیس -فلفل دلمه-قارچ-گوشت طعم دارشده -سس کچاپ',
        metaDescription:
          'خمیرمخصوص -سس مخصوص-کالباس مخصوص-پنیرپیتزامخصوص -سوسیس -فلفل دلمه-قارچ-گوشت طعم دارشده -سس کچاپ',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 3,
        localProductId: 28,
        active: true,
        displayOrder: 10,
        price: 700000,
        discountPrice: 595000,
        oldPrice: 0,
        smallImageName: '1041-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1041-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:14',
        display: false,
        category: {
          id: 212,
          topic: 'پیتزا',
          topicEn: '',
          topicAr: '',
          localCategoryId: 3,
          active: true,
          displayOrder: 2,
          imageName: 'C-212.png',
          imageLastUpdate: '2022-10-18 17:13:07',
        },
        bespokens: [
          {
            id: 20,
            topic: 'بدون قارچ',
            price: 0,
            localBespokenId: 4,
            active: true,
          },
          {
            id: 21,
            topic: 'بدون فلفل',
            price: 0,
            localBespokenId: 5,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1042,
        topic: 'پیتزا مینی گوشت و قارچ',
        topicEn: '',
        topicAr: '',
        description:
          'خمیرمخصوص -سس مخصوص -گوشت طعم دارشده-پنیرپیتزامخصوص-فلفل دلمه-قارچ-سس کچاپ',
        metaDescription:
          'خمیرمخصوص -سس مخصوص -گوشت طعم دارشده-پنیرپیتزامخصوص-فلفل دلمه-قارچ-سس کچاپ',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 3,
        localProductId: 29,
        active: true,
        displayOrder: 11,
        price: 800000,
        discountPrice: 680000,
        oldPrice: 0,
        smallImageName: '1042-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1042-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:15',
        display: false,
        category: {
          id: 212,
          topic: 'پیتزا',
          topicEn: '',
          topicAr: '',
          localCategoryId: 3,
          active: true,
          displayOrder: 2,
          imageName: 'C-212.png',
          imageLastUpdate: '2022-10-18 17:13:07',
        },
        bespokens: [
          {
            id: 21,
            topic: 'بدون فلفل',
            price: 0,
            localBespokenId: 5,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1044,
        topic: 'سیب زمینی',
        topicEn: '',
        topicAr: '',
        description: '',
        metaDescription: '',
        descriptionEn: '',
        descriptionAr: '',
        localCategoryId: 4,
        localProductId: 31,
        active: true,
        price: 300000,
        discountPrice: 300000,
        oldPrice: 0,
        smallImageName: '1044-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1044-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:16',
        display: false,
        category: {
          id: 213,
          topic: 'پیش غذا',
          topicEn: '',
          topicAr: '',
          localCategoryId: 4,
          active: true,
          displayOrder: 5,
          imageName: 'C-213.png',
          imageLastUpdate: '2022-10-18 17:12:48',
        },
        bespokens: [],
        productImages: [],
      },
      {
        id: 1045,
        topic: 'سیب زمینی قارچ و پنیر',
        topicEn: '',
        topicAr: '',
        description: '',
        metaDescription: '',
        descriptionEn: '',
        descriptionAr: '',
        localCategoryId: 4,
        localProductId: 32,
        active: true,
        price: 450000,
        discountPrice: 450000,
        oldPrice: 0,
        smallImageName: '1045-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1045-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:16',
        display: false,
        category: {
          id: 213,
          topic: 'پیش غذا',
          topicEn: '',
          topicAr: '',
          localCategoryId: 4,
          active: true,
          displayOrder: 5,
          imageName: 'C-213.png',
          imageLastUpdate: '2022-10-18 17:12:48',
        },
        bespokens: [],
        productImages: [],
      },
      {
        id: 1046,
        topic: 'سالاد فصل',
        topicEn: '',
        topicAr: '',
        description: '',
        metaDescription: '',
        descriptionEn: '',
        descriptionAr: '',
        localCategoryId: 4,
        localProductId: 33,
        active: true,
        price: 220000,
        discountPrice: 220000,
        oldPrice: 0,
        smallImageName: '1046-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1046-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:17',
        display: false,
        category: {
          id: 213,
          topic: 'پیش غذا',
          topicEn: '',
          topicAr: '',
          localCategoryId: 4,
          active: true,
          displayOrder: 5,
          imageName: 'C-213.png',
          imageLastUpdate: '2022-10-18 17:12:48',
        },
        bespokens: [],
        productImages: [],
      },
      {
        id: 1049,
        topic: 'نوشابه قوطی کوکاکولا',
        topicEn: '',
        topicAr: '',
        description: '',
        metaDescription: '',
        descriptionEn: '',
        descriptionAr: '',
        localCategoryId: 5,
        localProductId: 36,
        active: true,
        displayOrder: 1,
        price: 120000,
        discountPrice: 120000,
        oldPrice: 0,
        smallImageName: '1049-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1049-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:18',
        display: false,
        category: {
          id: 214,
          topic: 'نوشیدنی',
          topicEn: '',
          topicAr: '',
          localCategoryId: 5,
          active: true,
          displayOrder: 7,
          imageName: 'C-214.png',
          imageLastUpdate: '2022-10-18 17:13:22',
        },
        bespokens: [],
        productImages: [],
      },
      {
        id: 1120,
        topic: 'نوشابه قوطی فانتا',
        topicEn: '',
        topicAr: '',
        description: '',
        metaDescription: '',
        descriptionEn: '',
        descriptionAr: '',
        localCategoryId: 5,
        localProductId: 52,
        active: true,
        displayOrder: 2,
        price: 120000,
        discountPrice: 120000,
        oldPrice: 0,
        smallImageName: '1120-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1120-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:33',
        display: false,
        category: {
          id: 214,
          topic: 'نوشیدنی',
          topicEn: '',
          topicAr: '',
          localCategoryId: 5,
          active: true,
          displayOrder: 7,
          imageName: 'C-214.png',
          imageLastUpdate: '2022-10-18 17:13:22',
        },
        bespokens: [],
        productImages: [],
      },
      {
        id: 1121,
        topic: 'نوشابه قوطی اسپرایت',
        topicEn: '',
        topicAr: '',
        description: '',
        metaDescription: '',
        descriptionEn: '',
        descriptionAr: '',
        localCategoryId: 5,
        localProductId: 53,
        active: true,
        displayOrder: 3,
        price: 120000,
        discountPrice: 120000,
        oldPrice: 0,
        smallImageName: '1121-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1121-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:34',
        display: false,
        category: {
          id: 214,
          topic: 'نوشیدنی',
          topicEn: '',
          topicAr: '',
          localCategoryId: 5,
          active: true,
          displayOrder: 7,
          imageName: 'C-214.png',
          imageLastUpdate: '2022-10-18 17:13:22',
        },
        bespokens: [],
        productImages: [],
      },
      {
        id: 1050,
        topic: 'دلستر قوطی',
        topicEn: '',
        topicAr: '',
        description: '',
        metaDescription: '',
        descriptionEn: '',
        descriptionAr: '',
        localCategoryId: 5,
        localProductId: 37,
        active: true,
        displayOrder: 4,
        price: 136000,
        discountPrice: 136000,
        oldPrice: 0,
        smallImageName: '1050-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1050-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:19',
        display: false,
        category: {
          id: 214,
          topic: 'نوشیدنی',
          topicEn: '',
          topicAr: '',
          localCategoryId: 5,
          active: true,
          displayOrder: 7,
          imageName: 'C-214.png',
          imageLastUpdate: '2022-10-18 17:13:22',
        },
        bespokens: [],
        productImages: [],
      },
      {
        id: 1048,
        topic: 'دوغ لیوانی',
        topicEn: '',
        topicAr: '',
        description: '',
        metaDescription: '',
        descriptionEn: '',
        descriptionAr: '',
        localCategoryId: 5,
        localProductId: 35,
        active: true,
        displayOrder: 5,
        price: 70000,
        discountPrice: 70000,
        oldPrice: 0,
        smallImageName: '1048-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1048-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:18',
        display: false,
        category: {
          id: 214,
          topic: 'نوشیدنی',
          topicEn: '',
          topicAr: '',
          localCategoryId: 5,
          active: true,
          displayOrder: 7,
          imageName: 'C-214.png',
          imageLastUpdate: '2022-10-18 17:13:22',
        },
        bespokens: [],
        productImages: [],
      },
      {
        id: 1047,
        topic: 'آب معدنی',
        topicEn: '',
        topicAr: '',
        description: '',
        metaDescription: '',
        descriptionEn: '',
        descriptionAr: '',
        localCategoryId: 5,
        localProductId: 34,
        active: true,
        displayOrder: 6,
        price: 40000,
        discountPrice: 40000,
        oldPrice: 0,
        smallImageName: '1047-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1047-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:17',
        display: false,
        category: {
          id: 214,
          topic: 'نوشیدنی',
          topicEn: '',
          topicAr: '',
          localCategoryId: 5,
          active: true,
          displayOrder: 7,
          imageName: 'C-214.png',
          imageLastUpdate: '2022-10-18 17:13:22',
        },
        bespokens: [],
        productImages: [],
      },
      {
        id: 1016,
        topic: 'سوسیس بندری',
        topicEn: '',
        topicAr: '',
        description:
          'نان ساندویچ -مخلفات سوسیس بندری -خیارشور -گوجه - کاهو -سس مایونز',
        metaDescription:
          'نان ساندویچ -مخلفات سوسیس بندری -خیارشور -گوجه - کاهو -سس مایونز',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 8,
        localProductId: 3,
        active: true,
        displayOrder: 1,
        price: 400000,
        discountPrice: 340000,
        oldPrice: 0,
        smallImageName: '1016-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1016-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:40:58',
        display: false,
        category: {
          id: 217,
          topic: 'ساندویچ',
          topicEn: '',
          topicAr: '',
          localCategoryId: 8,
          active: true,
          displayOrder: 4,
          imageName: 'C-217.png',
          imageLastUpdate: '2022-10-18 17:13:40',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 23,
            topic: 'پنیراضافه',
            price: 50000,
            localBespokenId: 7,
            active: true,
          },
          {
            id: 31,
            topic: 'بدون هیچی',
            price: 0,
            localBespokenId: 8,
            active: true,
          },
          {
            id: 32,
            topic: 'قارچ پنیر',
            price: 100000,
            localBespokenId: 9,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1030,
        topic: 'سوسیس کوکتل',
        topicEn: '',
        topicAr: '',
        description:
          'نان ساندویچ -سوسیس کوکتل -خیارشور -گوجه - کاهو -سس مایونز',
        metaDescription:
          'نان ساندویچ -سوسیس کوکتل -خیارشور -گوجه - کاهو -سس مایونز',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 8,
        localProductId: 17,
        active: true,
        displayOrder: 2,
        price: 350000,
        discountPrice: 297500,
        oldPrice: 0,
        smallImageName: '1030-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1030-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:08',
        display: false,
        category: {
          id: 217,
          topic: 'ساندویچ',
          topicEn: '',
          topicAr: '',
          localCategoryId: 8,
          active: true,
          displayOrder: 4,
          imageName: 'C-217.png',
          imageLastUpdate: '2022-10-18 17:13:40',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 23,
            topic: 'پنیراضافه',
            price: 50000,
            localBespokenId: 7,
            active: true,
          },
          {
            id: 31,
            topic: 'بدون هیچی',
            price: 0,
            localBespokenId: 8,
            active: true,
          },
          {
            id: 32,
            topic: 'قارچ پنیر',
            price: 100000,
            localBespokenId: 9,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1019,
        topic: 'میکس بندری جیگر مرغ',
        topicEn: '',
        topicAr: '',
        description:
          'نان ساندویچ -سوسیس بندری -جیگر مرغ طعم دار شده -خیارشور - گوجه -کاهو -سس مایونز',
        metaDescription:
          'نان ساندویچ -سوسیس بندری -جیگر مرغ طعم دار شده -خیارشور - گوجه -کاهو -سس مایونز',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 8,
        localProductId: 6,
        active: true,
        displayOrder: 4,
        price: 400000,
        discountPrice: 340000,
        oldPrice: 0,
        smallImageName: '1019-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1019-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:02',
        display: false,
        category: {
          id: 217,
          topic: 'ساندویچ',
          topicEn: '',
          topicAr: '',
          localCategoryId: 8,
          active: true,
          displayOrder: 4,
          imageName: 'C-217.png',
          imageLastUpdate: '2022-10-18 17:13:40',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 31,
            topic: 'بدون هیچی',
            price: 0,
            localBespokenId: 8,
            active: true,
          },
          {
            id: 32,
            topic: 'قارچ پنیر',
            price: 100000,
            localBespokenId: 9,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1024,
        topic: 'جیگرمرغ',
        topicEn: '',
        topicAr: '',
        description:
          'نان ساندویچ-جیگرمرغ طعم دارشده خیارشور-گوجه -کاهو-سس مایونز-',
        metaDescription:
          'نان ساندویچ-جیگرمرغ طعم دارشده خیارشور-گوجه -کاهو-سس مایونز-',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 8,
        localProductId: 11,
        active: true,
        displayOrder: 5,
        price: 350000,
        discountPrice: 297500,
        oldPrice: 0,
        smallImageName: '1024-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1024-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:05',
        display: false,
        category: {
          id: 217,
          topic: 'ساندویچ',
          topicEn: '',
          topicAr: '',
          localCategoryId: 8,
          active: true,
          displayOrder: 4,
          imageName: 'C-217.png',
          imageLastUpdate: '2022-10-18 17:13:40',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 31,
            topic: 'بدون هیچی',
            price: 0,
            localBespokenId: 8,
            active: true,
          },
          {
            id: 32,
            topic: 'قارچ پنیر',
            price: 100000,
            localBespokenId: 9,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1020,
        topic: 'فلافل قارچ و ‍‍پنیر',
        topicEn: '',
        topicAr: '',
        description:
          'نان ساندویچ -فلافل -قارچ -پنیر مخصوص -خیارشور -گوجه -کاهو -سس کچاپ -سس مایونز',
        metaDescription:
          'نان ساندویچ -فلافل -قارچ -پنیر مخصوص -خیارشور -گوجه -کاهو -سس کچاپ -سس مایونز',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 8,
        localProductId: 7,
        active: true,
        displayOrder: 6,
        price: 400000,
        discountPrice: 340000,
        oldPrice: 0,
        smallImageName: '1020-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1020-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:03',
        display: false,
        category: {
          id: 217,
          topic: 'ساندویچ',
          topicEn: '',
          topicAr: '',
          localCategoryId: 8,
          active: true,
          displayOrder: 4,
          imageName: 'C-217.png',
          imageLastUpdate: '2022-10-18 17:13:40',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 23,
            topic: 'پنیراضافه',
            price: 50000,
            localBespokenId: 7,
            active: true,
          },
          {
            id: 31,
            topic: 'بدون هیچی',
            price: 0,
            localBespokenId: 8,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1022,
        topic: 'هات داگ',
        topicEn: '',
        topicAr: '',
        description:
          'نان هات داگ -1عدد سوسیس هات داگ - خیارشور -گوجه -کاهو - سس کچاپ -سس مایونز',
        metaDescription:
          'نان هات داگ -1عدد سوسیس هات داگ - خیارشور -گوجه -کاهو - سس کچاپ -سس مایونز',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 8,
        localProductId: 9,
        active: true,
        displayOrder: 7,
        price: 500000,
        discountPrice: 425000,
        oldPrice: 0,
        smallImageName: '1022-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1022-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:04',
        display: false,
        category: {
          id: 217,
          topic: 'ساندویچ',
          topicEn: '',
          topicAr: '',
          localCategoryId: 8,
          active: true,
          displayOrder: 4,
          imageName: 'C-217.png',
          imageLastUpdate: '2022-10-18 17:13:40',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 31,
            topic: 'بدون هیچی',
            price: 0,
            localBespokenId: 8,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1023,
        topic: 'رویال هات داگ',
        topicEn: '',
        topicAr: '',
        description:
          'نان هات داگ -1عددسوسیس هات داگ-1ورق کالباس ژامبون -1عدد پنیر ورقه ای -خیارشور      -گوجه -کاهو -سس کچاپ -سس مایونز',
        metaDescription:
          'نان هات داگ -1عددسوسیس هات داگ-1ورق کالباس ژامبون -1عدد پنیر ورقه ای -خیارشور      -گوجه -کاهو -سس کچاپ -سس مایونز',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 8,
        localProductId: 10,
        active: true,
        displayOrder: 8,
        price: 600000,
        discountPrice: 510000,
        oldPrice: 0,
        smallImageName: '1023-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1023-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:04',
        display: false,
        category: {
          id: 217,
          topic: 'ساندویچ',
          topicEn: '',
          topicAr: '',
          localCategoryId: 8,
          active: true,
          displayOrder: 4,
          imageName: 'C-217.png',
          imageLastUpdate: '2022-10-18 17:13:40',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 23,
            topic: 'پنیراضافه',
            price: 50000,
            localBespokenId: 7,
            active: true,
          },
          {
            id: 31,
            topic: 'بدون هیچی',
            price: 0,
            localBespokenId: 8,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1034,
        topic: 'هات داگ قارچ و پنیر',
        topicEn: '',
        topicAr: '',
        description:
          'نان هات داگ -1عدد سوسیس هات داگ -قارچ پنیر مخصوص -خیارشور -گوجه -کاهو -سس کچاپ -سس مایونز',
        metaDescription:
          'نان هات داگ -1عدد سوسیس هات داگ -قارچ پنیر مخصوص -خیارشور -گوجه -کاهو -سس کچاپ -سس مایونز',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 8,
        localProductId: 21,
        active: true,
        displayOrder: 9,
        price: 600000,
        discountPrice: 510000,
        oldPrice: 0,
        smallImageName: '1034-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1034-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:10',
        display: false,
        category: {
          id: 217,
          topic: 'ساندویچ',
          topicEn: '',
          topicAr: '',
          localCategoryId: 8,
          active: true,
          displayOrder: 4,
          imageName: 'C-217.png',
          imageLastUpdate: '2022-10-18 17:13:40',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 23,
            topic: 'پنیراضافه',
            price: 50000,
            localBespokenId: 7,
            active: true,
          },
          {
            id: 31,
            topic: 'بدون هیچی',
            price: 0,
            localBespokenId: 8,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1032,
        topic: 'استیک مرغ',
        topicEn: '',
        topicAr: '',
        description:
          'نان ساندویچ-فیله مرغ طعم دارشده خیارشور-گوجه -کاهو-سس مایونز-سس کچاپ',
        metaDescription:
          'نان ساندویچ-فیله مرغ طعم دارشده خیارشور-گوجه -کاهو-سس مایونز-سس کچاپ',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 8,
        localProductId: 19,
        active: true,
        displayOrder: 10,
        price: 500000,
        discountPrice: 425000,
        oldPrice: 0,
        smallImageName: '1032-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1032-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:09',
        display: false,
        category: {
          id: 217,
          topic: 'ساندویچ',
          topicEn: '',
          topicAr: '',
          localCategoryId: 8,
          active: true,
          displayOrder: 4,
          imageName: 'C-217.png',
          imageLastUpdate: '2022-10-18 17:13:40',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 31,
            topic: 'بدون هیچی',
            price: 0,
            localBespokenId: 8,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1035,
        topic: 'رویال مرغ',
        topicEn: '',
        topicAr: '',
        description:
          'نان ساندویچ-فیله مرغ طعم دارشده -1ورق ژامبون -1عددپنیرورقه ای خیارشور-گوجه -کاهو-سس مایونز-سس کچاپ',
        metaDescription:
          'نان ساندویچ-فیله مرغ طعم دارشده -1ورق ژامبون -1عددپنیرورقه ای خیارشور-گوجه -کاهو-سس مایونز-سس کچاپ',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 8,
        localProductId: 22,
        active: true,
        displayOrder: 11,
        price: 700000,
        discountPrice: 595000,
        oldPrice: 0,
        smallImageName: '1035-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1035-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:11',
        display: false,
        category: {
          id: 217,
          topic: 'ساندویچ',
          topicEn: '',
          topicAr: '',
          localCategoryId: 8,
          active: true,
          displayOrder: 4,
          imageName: 'C-217.png',
          imageLastUpdate: '2022-10-18 17:13:40',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 23,
            topic: 'پنیراضافه',
            price: 50000,
            localBespokenId: 7,
            active: true,
          },
          {
            id: 31,
            topic: 'بدون هیچی',
            price: 0,
            localBespokenId: 8,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1025,
        topic: 'مرغ قارچ',
        topicEn: '',
        topicAr: '',
        description:
          'نان ساندویچ -فیله مرغ طعم دارشده -قارچ -پنیر مخصوص -خیارشور -گوجه -کاهو -سس کچاپ -سس مایونز',
        metaDescription:
          'نان ساندویچ -فیله مرغ طعم دارشده -قارچ -پنیر مخصوص -خیارشور -گوجه -کاهو -سس کچاپ -سس مایونز',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 8,
        localProductId: 12,
        active: true,
        displayOrder: 12,
        price: 700000,
        discountPrice: 595000,
        oldPrice: 0,
        smallImageName: '1025-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1025-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:05',
        display: false,
        category: {
          id: 217,
          topic: 'ساندویچ',
          topicEn: '',
          topicAr: '',
          localCategoryId: 8,
          active: true,
          displayOrder: 4,
          imageName: 'C-217.png',
          imageLastUpdate: '2022-10-18 17:13:40',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 23,
            topic: 'پنیراضافه',
            price: 50000,
            localBespokenId: 7,
            active: true,
          },
          {
            id: 31,
            topic: 'بدون هیچی',
            price: 0,
            localBespokenId: 8,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1021,
        topic: 'استیک گوشت',
        topicEn: '',
        topicAr: '',
        description:
          'نان ساندویچ-گوشت فیله گوساله طعم دارشده خیارشور-گوجه -کاهو-سس مایونز-سس کچاپ',
        metaDescription:
          'نان ساندویچ-گوشت فیله گوساله طعم دارشده خیارشور-گوجه -کاهو-سس مایونز-سس کچاپ',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 8,
        localProductId: 8,
        active: true,
        displayOrder: 13,
        price: 650000,
        discountPrice: 552500,
        oldPrice: 0,
        smallImageName: '1021-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1021-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:03',
        display: false,
        category: {
          id: 217,
          topic: 'ساندویچ',
          topicEn: '',
          topicAr: '',
          localCategoryId: 8,
          active: true,
          displayOrder: 4,
          imageName: 'C-217.png',
          imageLastUpdate: '2022-10-18 17:13:40',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
          {
            id: 31,
            topic: 'بدون هیچی',
            price: 0,
            localBespokenId: 8,
            active: true,
          },
        ],
        productImages: [],
      },
      {
        id: 1033,
        topic: 'کالباس مخصوص',
        topicEn: '',
        topicAr: '',
        description:
          'نان ساندویچ -کالباس ژامبون -خیارشور -گوجه -کاهو -سس کچاپ -سس مایونز',
        metaDescription:
          'نان ساندویچ -کالباس ژامبون -خیارشور -گوجه -کاهو -سس کچاپ -سس مایونز',
        descriptionEn: '',
        descriptionAr: '',
        discountPercent: 15,
        localCategoryId: 8,
        localProductId: 20,
        active: true,
        displayOrder: 14,
        price: 350000,
        discountPrice: 297500,
        oldPrice: 0,
        smallImageName: '1033-S.jpg',
        smallImageUrl: 'https://store.nikukiosk.com/image/1033-S.jpg',
        smallImageLastUpdate: '2022-09-21 12:41:10',
        display: false,
        category: {
          id: 217,
          topic: 'ساندویچ',
          topicEn: '',
          topicAr: '',
          localCategoryId: 8,
          active: true,
          displayOrder: 4,
          imageName: 'C-217.png',
          imageLastUpdate: '2022-10-18 17:13:40',
        },
        bespokens: [
          {
            id: 17,
            topic: 'بدون گوجه',
            price: 0,
            localBespokenId: 1,
            active: true,
          },
          {
            id: 19,
            topic: 'بدون کاهو',
            price: 0,
            localBespokenId: 3,
            active: true,
          },
          {
            id: 22,
            topic: 'نان اضافه',
            price: 40000,
            localBespokenId: 6,
            active: true,
          },
        ],
        productImages: [],
      },
    ],
  },
};
